Moon Surface Illumination Simulation Framework: MoonIllumSim::Spacecraft Class Reference
MoonIllumSim::Spacecraft Class Reference
Public Member Functions
int addSpacecraftState (double time)
double getArgumentOfPeriapsis ()
double getEccentricity ()
double getEpoch ()
string getEpochAsUTCString ()
double getFixedTime ()
double getInclination ()
Quaternion getInitialOrientation ()
KeplerOrbit getKeplerOrbit ()
double getLongOfAscNode ()
double getMeanAnomalyAtEpoch ()
Vector3D getOrientationTransition ()
double getSemiMajorAxis ()
SpacecraftState getSpacecraftState (int i)
bool isOrientationGiven ()
void setEpoch (double epoch)
void setFixedTime (double time)
void setKeplerOrbitParameters (double a, double e, double omega, double Omega, double i, double M0)
void setOrientation (Quaternion orientation)
void setOrientationTransition (Vector3D trans)
void setPosition (Vector3D r)
void setStateVectors (Vector3D r, Vector3D dr)
Public Attributes
Vector3D _fixed_position = new Vector3D(0, 0, 0)
bool fixedPositionGiven = false
Protected Attributes
Quaternion _initial_orientation = new Quaternion(1,0,0,0)
KeplerOrbit _kepler_orbit = new KeplerOrbit()
Vector3D _orientation_transition = new Vector3D(0,0,0)
bool orientation_given = false
Private Attributes
double _fixed_simulation_time = 0
Dictionary< Int32,
SpacecraftState > _spacecraft_state = new Dictionary<Int32, SpacecraftState>()
Member Function Documentation
int MoonIllumSim::Spacecraft::addSpacecraftState (double time) [inline]
Definition at line 109 of file Spacecraft.cs.
References _spacecraft_state.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic().
        {
            Int32 id = this._spacecraft_state.Count + 1;
            this._spacecraft_state.Add(id, new SpacecraftState(this));
            this._spacecraft_state[id].setTime(time);
            return id;
        }
double MoonIllumSim::Spacecraft::getArgumentOfPeriapsis () [inline]
Definition at line 57 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getArgumentOfPeriapsis().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getArgumentOfPeriapsis();
        }
double MoonIllumSim::Spacecraft::getEccentricity () [inline]
Definition at line 52 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getEccentricity().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getEccentricity();
        }
double MoonIllumSim::Spacecraft::getEpoch () [inline]
Definition at line 25 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getEpoch().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getEpoch();
        }
string MoonIllumSim::Spacecraft::getEpochAsUTCString () [inline]
Definition at line 30 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getEpochAsUTCString().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getEpochAsUTCString();
        }
double MoonIllumSim::Spacecraft::getFixedTime () [inline]
Definition at line 137 of file Spacecraft.cs.
References _fixed_simulation_time.
Referenced by MoonIllumSim::Simulation.doCalculations().
        {
            return this._fixed_simulation_time;
        }
double MoonIllumSim::Spacecraft::getInclination () [inline]
Definition at line 67 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getInclination().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getInclination();
        }
Quaternion MoonIllumSim::Spacecraft::getInitialOrientation () [inline]
Definition at line 94 of file Spacecraft.cs.
References _initial_orientation.
Referenced by MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._initial_orientation;
        }
KeplerOrbit MoonIllumSim::Spacecraft::getKeplerOrbit () [inline]
Definition at line 117 of file Spacecraft.cs.
References _kepler_orbit.
Referenced by MoonIllumSim::SpacecraftState.SpacecraftState().
        {
            return this._kepler_orbit;
        }
double MoonIllumSim::Spacecraft::getLongOfAscNode () [inline]
Definition at line 62 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getLongOfAscNode().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getLongOfAscNode();
        }
double MoonIllumSim::Spacecraft::getMeanAnomalyAtEpoch () [inline]
Definition at line 72 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getMeanAnomalyAtEpoch().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getMeanAnomalyAtEpoch();
        }
Vector3D MoonIllumSim::Spacecraft::getOrientationTransition () [inline]
Definition at line 104 of file Spacecraft.cs.
References _orientation_transition.
Referenced by MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._orientation_transition;
        }
double MoonIllumSim::Spacecraft::getSemiMajorAxis () [inline]
Definition at line 47 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.getSemiMajorAxis().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getSemiMajorAxis();
        }
SpacecraftState MoonIllumSim::Spacecraft::getSpacecraftState (int i) [inline]
Definition at line 122 of file Spacecraft.cs.
References _spacecraft_state.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic().
        {
            return this._spacecraft_state[i];
        }
bool MoonIllumSim::Spacecraft::isOrientationGiven () [inline]
Definition at line 127 of file Spacecraft.cs.
References orientation_given.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), MoonIllumSim::Simulation.generatePOVRayFile(), MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this.orientation_given;
        }
void MoonIllumSim::Spacecraft::setEpoch (double epoch) [inline]
Definition at line 20 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.setEpoch().
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._kepler_orbit.setEpoch(epoch);
        }
void MoonIllumSim::Spacecraft::setFixedTime (double time) [inline]
Definition at line 132 of file Spacecraft.cs.
References _fixed_simulation_time.
Referenced by MoonIllumSim::Simulation.setBatchSet().
        {
            this._fixed_simulation_time = time;
        }
void MoonIllumSim::Spacecraft::setKeplerOrbitParameters (double a, double e, double omega, double Omega, double i, double M0) [inline]
Definition at line 35 of file Spacecraft.cs.
References _kepler_orbit, and MoonIllumSim::KeplerOrbit.setKeplerElements().
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            try
            {
                this._kepler_orbit.setKeplerElements(a, e, omega, Omega, i, M0);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
void MoonIllumSim::Spacecraft::setOrientation (Quaternion orientation) [inline]
Definition at line 88 of file Spacecraft.cs.
References _initial_orientation, and orientation_given.
Referenced by MoonIllumSim::Simulation.setBatchSet(), and MoonIllumSim::tools.parse_arguments().
        {
            this._initial_orientation = orientation;
            this.orientation_given = true;
        }
void MoonIllumSim::Spacecraft::setOrientationTransition (Vector3D trans) [inline]
Definition at line 99 of file Spacecraft.cs.
References _orientation_transition.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._orientation_transition = trans;
        }
void MoonIllumSim::Spacecraft::setPosition (Vector3D r) [inline]
Definition at line 82 of file Spacecraft.cs.
References _fixed_position, and fixedPositionGiven.
Referenced by MoonIllumSim::Simulation.setBatchSet().
        {
            this._fixed_position = r;
            this.fixedPositionGiven = true;
        }
void MoonIllumSim::Spacecraft::setStateVectors (Vector3D r, Vector3D dr) [inline]
Definition at line 77 of file Spacecraft.cs.
References _kepler_orbit.
Referenced by MoonIllumSim::Simulation.setBatchSet(), and MoonIllumSim::tools.parse_arguments().
        {
            this._kepler_orbit = new KeplerOrbit(r, dr);
        }
Member Data Documentation
Vector3D MoonIllumSim::Spacecraft::_fixed_position = new Vector3D(0, 0, 0)
Definition at line 12 of file Spacecraft.cs.
Referenced by setPosition(), MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::SpacecraftState.setTime().
double MoonIllumSim::Spacecraft::_fixed_simulation_time = 0 [private]
Definition at line 18 of file Spacecraft.cs.
Referenced by setFixedTime(), and getFixedTime().
Quaternion MoonIllumSim::Spacecraft::_initial_orientation = new Quaternion(1,0,0,0) [protected]
Definition at line 13 of file Spacecraft.cs.
Referenced by setOrientation(), getInitialOrientation(), MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::SpacecraftState.setTime().
KeplerOrbit MoonIllumSim::Spacecraft::_kepler_orbit = new KeplerOrbit() [protected]
Definition at line 11 of file Spacecraft.cs.
Referenced by setEpoch(), getEpoch(), getEpochAsUTCString(), setKeplerOrbitParameters(), getSemiMajorAxis(), getEccentricity(), getArgumentOfPeriapsis(), getLongOfAscNode(), getInclination(), getMeanAnomalyAtEpoch(), setStateVectors(), getKeplerOrbit(), MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::SpacecraftState.setTime().
Vector3D MoonIllumSim::Spacecraft::_orientation_transition = new Vector3D(0,0,0) [protected]
Definition at line 14 of file Spacecraft.cs.
Referenced by setOrientationTransition(), getOrientationTransition(), MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::SpacecraftState.setTime().
Dictionary<Int32, SpacecraftState> MoonIllumSim::Spacecraft::_spacecraft_state = new Dictionary<Int32, SpacecraftState>() [private]
Definition at line 15 of file Spacecraft.cs.
Referenced by addSpacecraftState(), and getSpacecraftState().
bool MoonIllumSim::Spacecraft::fixedPositionGiven = false
Definition at line 17 of file Spacecraft.cs.
Referenced by setPosition(), MoonIllumSim::SpacecraftState.SpacecraftState(), and MoonIllumSim::SpacecraftState.setTime().
bool MoonIllumSim::Spacecraft::orientation_given = false [protected]
Definition at line 16 of file Spacecraft.cs.
Referenced by setOrientation(), isOrientationGiven(), and MoonIllumSim::SpacecraftState.SpacecraftState().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/Spacecraft.cs