Moon Surface Illumination Simulation Framework: MoonIllumSim::Program Class Reference
MoonIllumSim::Program Class Reference
Static Public Attributes
static bool batchmode = false
static bool batchSet = false
static bool checkOrbit = false
static bool checkTime = false
static bool checkTimeT0 = false
static string scientificFormat = "+0.000000000000000E+000;-0.000000000000000E+000"
static Simulation sim = new Simulation()
Static Private Member Functions
static void Main (string[] args)
Member Function Documentation
static void MoonIllumSim::Program::Main (string[] args) [inline, static, private]
Definition at line 29 of file Program.cs.
References MoonIllumSim::tools.output_header(), MoonIllumSim::tools.parse_arguments(), sim, MoonIllumSim::Simulation.checkConfig(), MoonIllumSim::tools.display_help(), MoonIllumSim::tools.output_configuration_overview(), MoonIllumSim::Simulation.doCalculations(), and batchmode.
        {
            try
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
                tools.output_header();
                tools.parse_arguments(args);
                sim.checkConfig();
            }
            catch (Exception e)
            {
                if (e.Message == "")
                {
                    tools.display_help();
                }
                else
                {
                    Console.WriteLine("ERROR:");
                    Console.WriteLine(e.Message);
                    Console.WriteLine();
                    Console.WriteLine("Display help to your support:\n");
                    tools.display_help();
                }
                return;
            }
            tools.output_configuration_overview();
            try
            {
                sim.doCalculations();
            }
            catch (Exception e)
            {
                Console.WriteLine("ERROR:");
                Console.WriteLine(e.Message);
            }
            if (!batchmode)
            {
                Console.WriteLine("\nPress any key to exit...");
                //cin.get();
            }
            return;
        }
Member Data Documentation
bool MoonIllumSim::Program::batchmode = false [static]
Definition at line 21 of file Program.cs.
Referenced by Main(), MoonIllumSim::tools.parse_arguments(), and MoonIllumSim::tools.output_configuration_overview().
bool MoonIllumSim::Program::batchSet = false [static]
Definition at line 26 of file Program.cs.
Referenced by MoonIllumSim::Simulation.doCalculations(), MoonIllumSim::tools.parse_arguments(), and MoonIllumSim::tools.output_configuration_overview().
bool MoonIllumSim::Program::checkOrbit = false [static]
Definition at line 25 of file Program.cs.
Referenced by MoonIllumSim::tools.parse_arguments().
bool MoonIllumSim::Program::checkTime = false [static]
Definition at line 23 of file Program.cs.
Referenced by MoonIllumSim::tools.parse_arguments().
bool MoonIllumSim::Program::checkTimeT0 = false [static]
Definition at line 24 of file Program.cs.
Referenced by MoonIllumSim::tools.parse_arguments().
string MoonIllumSim::Program::scientificFormat = "+0.000000000000000E+000;-0.000000000000000E+000" [static]
Definition at line 27 of file Program.cs.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::tools.output_configuration_overview().
Simulation MoonIllumSim::Program::sim = new Simulation() [static]
Definition at line 22 of file Program.cs.
Referenced by Main(), MoonIllumSim::tools.parse_arguments(), and MoonIllumSim::tools.output_configuration_overview().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/Program.cs