Moon Surface Illumination Simulation Framework: MoonIllumSim::RotationQuaternion Class Reference
MoonIllumSim::RotationQuaternion Class Reference
Public Member Functions
Quaternion conjugate ()
Vector3D getVector ()
bool isPure ()
double Norm ()
double r ()
RotationQuaternion (Vector3D axis, double angle)
Vector3D v ()
Static Public Member Functions
static Quaternion operator* (Quaternion q1, Quaternion q2)
static Quaternion operator+ (Quaternion q1, Quaternion q2)
Protected Attributes
double _r = 0
quaternion real part
Vector3D _v = new Vector3D(0,0,0)
quaternion vector part
Constructor & Destructor Documentation
MoonIllumSim::RotationQuaternion::RotationQuaternion (Vector3D axis, double angle) [inline]
Definition at line 10 of file RotationQuaternion.cs.
References MoonIllumSim::Quaternion._r, MoonIllumSim::Quaternion._v, MoonIllumSim::Vector3D.x(), MoonIllumSim::Vector3D.y(), and MoonIllumSim::Vector3D.z().
        {
            double sinCoeff = Math.Sin(angle / 2);
            this._r = Math.Cos(angle / 2);
            this._v = new Vector3D( axis.x() * sinCoeff,
                                    axis.y() * sinCoeff,
                                    axis.z() * sinCoeff);
        }
Member Function Documentation
Quaternion MoonIllumSim::Quaternion::conjugate () [inline, inherited]
Definition at line 93 of file Quaternion.cs.
References MoonIllumSim::Quaternion.Quaternion(), MoonIllumSim::Quaternion._r, and MoonIllumSim::Quaternion._v.
Referenced by MoonIllumSim::Vector3D.QuaternionRotate().
        {
            return new Quaternion(this._r, -this._v);
        }
Vector3D MoonIllumSim::Quaternion::getVector () [inline, inherited]
Definition at line 98 of file Quaternion.cs.
References MoonIllumSim::Quaternion.isPure(), and MoonIllumSim::Quaternion._v.
Referenced by MoonIllumSim::Vector3D.QuaternionRotate().
        {
            if (this.isPure())
            {
                return this._v;
            }
            else
            {
                throw new Exception("Error returning vector from Quaternion: Quaternion is not an pure Quaternion.");
            }
        }
bool MoonIllumSim::Quaternion::isPure () [inline, inherited]
Definition at line 110 of file Quaternion.cs.
Referenced by MoonIllumSim::Quaternion.getVector().
        {
            /*
            if (this._r == 0)
            {
                return true;
            }
            else
            {
                return false;
            }*/
            return true;
        }
double MoonIllumSim::Quaternion::Norm () [inline, inherited]
Definition at line 124 of file Quaternion.cs.
References MoonIllumSim::Quaternion._r, MoonIllumSim::Quaternion._v, MoonIllumSim::Vector3D.x(), MoonIllumSim::Vector3D.y(), and MoonIllumSim::Vector3D.z().
        {
            return Math.Sqrt((this._r * this._r) + (this._v.x() * this._v.x()) + (this._v.y() * this._v.y()) + (this._v.z() * this._v.z()));
        }
static Quaternion MoonIllumSim::Quaternion::operator* (Quaternion q1, Quaternion q2) [inline, static, inherited]
Definition at line 75 of file Quaternion.cs.
References MoonIllumSim::Quaternion.Quaternion().
        {
            return new Quaternion(  q1.r() * q2.r() - q1.v().x() * q2.v().x() - q1.v().y() * q2.v().y() - q1.v().z() * q2.v().z(),
                                    q1.r() * q2.v().x() + q1.v().x() * q2.r() + q1.v().y() * q2.v().z() - q1.v().z() * q2.v().y(),
                                    q1.r() * q2.v().y() - q1.v().x() * q2.v().z() + q1.v().y() * q2.r() + q1.v().z() * q2.v().x(),
                                    q1.r() * q2.v().z() + q1.v().x() * q2.v().y() - q1.v().y() * q2.v().x() + q1.v().z() * q2.r());
        }
static Quaternion MoonIllumSim::Quaternion::operator+ (Quaternion q1, Quaternion q2) [inline, static, inherited]
Definition at line 70 of file Quaternion.cs.
References MoonIllumSim::Quaternion.Quaternion().
        {
            return new Quaternion(q1.r() + q2.r(), q1.v() + q2.v());
        }
double MoonIllumSim::Quaternion::r () [inline, inherited]
Definition at line 83 of file Quaternion.cs.
References MoonIllumSim::Quaternion._r.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._r;
        }
Vector3D MoonIllumSim::Quaternion::v () [inline, inherited]
Definition at line 88 of file Quaternion.cs.
References MoonIllumSim::Quaternion._v.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._v;
        }
Member Data Documentation
double MoonIllumSim::Quaternion::_r = 0 [protected, inherited]
quaternion real part
Definition at line 31 of file Quaternion.cs.
Referenced by MoonIllumSim::Quaternion.Quaternion(), MoonIllumSim::Quaternion.r(), MoonIllumSim::Quaternion.conjugate(), MoonIllumSim::Quaternion.Norm(), and RotationQuaternion().
Vector3D MoonIllumSim::Quaternion::_v = new Vector3D(0,0,0) [protected, inherited]
quaternion vector part
Definition at line 36 of file Quaternion.cs.
Referenced by MoonIllumSim::Quaternion.Quaternion(), MoonIllumSim::Quaternion.v(), MoonIllumSim::Quaternion.conjugate(), MoonIllumSim::Quaternion.getVector(), MoonIllumSim::Quaternion.Norm(), and RotationQuaternion().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/RotationQuaternion.cs