Moon Surface Illumination Simulation Framework: MoonIllumSim::KeplerOrbit Class Reference
MoonIllumSim::KeplerOrbit Class Reference
Public Member Functions
double getArgumentOfPeriapsis ()
double getEccentricity ()
double getEpoch ()
string getEpochAsUTCString ()
double getInclination ()
double getLongOfAscNode ()
double getMeanAnomalyAtEpoch ()
Vector3D getPosition (double t)
double getSemiMajorAxis ()
KeplerOrbit ()
KeplerOrbit (Vector3D r, Vector3D dr)
void setEpoch (double epoch)
void setKeplerElements (double a, double e, double omega, double Omega, double i, double M0)
void setKeplerElements (double epoch, double a, double e, double omega, double Omega, double i, double M0)
Protected Member Functions
void _set_a (double a)
void _set_e (double e)
void _set_i (double i)
void _set_M0 (double M0)
void _set_omega (double omega)
void _set_Omega (double Omega)
Private Attributes
double _a = 2000000 + _moon_radius
double _e = 1
double _epoch = 51544.5
const double _GM = 4.90277790e+012
double _i = 0
double _M0 = 0
const double _moon_radius = 1737400
double _omega = 0
double _Omega = 0
Constructor & Destructor Documentation
MoonIllumSim::KeplerOrbit::KeplerOrbit () [inline]
Definition at line 21 of file KeplerOrbit.cs.
{ }
MoonIllumSim::KeplerOrbit::KeplerOrbit (Vector3D r, Vector3D dr) [inline]
Definition at line 58 of file KeplerOrbit.cs.
References _GM, MoonIllumSim::Vector3D.norm(), MoonIllumSim::Vector3D.z(), MoonIllumSim::Vector3D.y(), MoonIllumSim::Vector3D.x(), and setKeplerElements().
        {
            Vector3D h = r % dr;
            Vector3D ev = ((dr % h) / _GM) - (r / r.norm());
            Vector3D n = new Vector3D(0, 0, 1) % h;
            double nu = 0;
            if (r * dr >= 0)
            {
                nu = Math.Acos((ev * r) / (ev.norm() * r.norm()));
            }
            else
            {
                nu = (2*Math.PI - Math.Acos((ev * r) / (ev.norm() * r.norm())));
            }
            double E = Math.Acos((ev.norm() + Math.Cos(nu)) / (1 + (ev.norm() * Math.Cos(nu))));
            double i = Math.Acos(h.z()/h.norm());
            double e = ev.norm();
            double Omega = 0;
            if (n.y() >= 0)
            {
                Omega = Math.Acos(n.x() / n.norm());
            }
            else
            {
                Omega = 2*Math.PI - Math.Acos(n.x() / n.norm());
            }
            double omega = 0;
            if (ev.z() >= 0)
            {
                omega = Math.Acos((n*ev) / (n.norm()*ev.norm()));
            }
            else
            {
                omega = 2*Math.PI - Math.Acos((n * ev) / (n.norm() * ev.norm()));
            }
            double M = E - (e * Math.Sin(E));
            double a = 1 / ((2/r.norm()) - (Math.Pow(dr.norm(),2)/_GM));
            this.setKeplerElements(a, e, omega, Omega, i, M);
        }
Member Function Documentation
void MoonIllumSim::KeplerOrbit::_set_a (double a) [inline, protected]
Definition at line 145 of file KeplerOrbit.cs.
References _moon_radius, and _a.
Referenced by setKeplerElements().
        {
            if (a > _moon_radius)
            {
                this._a = a;
            }
            else
            {
                throw new Exception("S/C orbit shape error: Semi-major axis a is smaller than the Moon's radius.");
            }
        }
void MoonIllumSim::KeplerOrbit::_set_e (double e) [inline, protected]
Definition at line 157 of file KeplerOrbit.cs.
References _e.
Referenced by setKeplerElements().
        {
            if (e > 0 && e <= 1)
            {
                this._e = e;
            }
            else
            {
                throw new Exception("S/C orbit shape error: This software is not made to calculate non-circular/non-elliptic orbits.\nOrbit eccentricity e is not in ]0,1].");
            }
        }
void MoonIllumSim::KeplerOrbit::_set_i (double i) [inline, protected]
Definition at line 193 of file KeplerOrbit.cs.
References _i.
Referenced by setKeplerElements().
        {
            if (i >= 0 && i < 2 * Math.PI)
            {
                this._i = i;
            }
            else
            {
                throw new Exception("S/C orbit shape error: Inclination i is not in [0,2\\pi[.");
            }
        }
void MoonIllumSim::KeplerOrbit::_set_M0 (double M0) [inline, protected]
Definition at line 205 of file KeplerOrbit.cs.
References _M0.
Referenced by setKeplerElements().
        {
            if (M0 >= 0 && M0 < 2 * Math.PI)
            {
                this._M0 = M0;
            }
            else
            {
                throw new Exception("S/C orbit shape error: Mean anomaly M_0 at epoch t_0 is not in [0,2\\pi[.");
            }
        }
void MoonIllumSim::KeplerOrbit::_set_omega (double omega) [inline, protected]
Definition at line 169 of file KeplerOrbit.cs.
References _omega.
Referenced by setKeplerElements().
        {
            if (omega >= 0 && omega < 2*Math.PI)
            {
                this._omega = omega;
            }
            else
            {
                throw new Exception("S/C orbit shape error: Argument of periapsis omega is not in [0,2\\pi[.");
            }
        }
void MoonIllumSim::KeplerOrbit::_set_Omega (double Omega) [inline, protected]
Definition at line 181 of file KeplerOrbit.cs.
References _Omega.
Referenced by setKeplerElements().
        {
            if (Omega >= 0 && Omega < 2 * Math.PI)
            {
                this._Omega = Omega;
            }
            else
            {
                throw new Exception("S/C orbit shape error: Longitude of ascending node Omega is not in [0,2\\pi[.");
            }
        }
double MoonIllumSim::KeplerOrbit::getArgumentOfPeriapsis () [inline]
Definition at line 249 of file KeplerOrbit.cs.
References _omega.
Referenced by MoonIllumSim::Spacecraft.getArgumentOfPeriapsis().
        {
            return this._omega;
        }
double MoonIllumSim::KeplerOrbit::getEccentricity () [inline]
Definition at line 244 of file KeplerOrbit.cs.
References _e.
Referenced by MoonIllumSim::Spacecraft.getEccentricity().
        {
            return this._e;
        }
double MoonIllumSim::KeplerOrbit::getEpoch () [inline]
Definition at line 229 of file KeplerOrbit.cs.
References _epoch.
Referenced by MoonIllumSim::Spacecraft.getEpoch().
        {
            return this._epoch;
        }
string MoonIllumSim::KeplerOrbit::getEpochAsUTCString () [inline]
Definition at line 234 of file KeplerOrbit.cs.
References MoonIllumSim::tools.MJDtoUTC(), and _epoch.
Referenced by MoonIllumSim::Spacecraft.getEpochAsUTCString().
        {
            return tools.MJDtoUTC(this._epoch).ToString("s");
        }
double MoonIllumSim::KeplerOrbit::getInclination () [inline]
Definition at line 259 of file KeplerOrbit.cs.
References _i.
Referenced by MoonIllumSim::Spacecraft.getInclination().
        {
            return this._i;
        }
double MoonIllumSim::KeplerOrbit::getLongOfAscNode () [inline]
Definition at line 254 of file KeplerOrbit.cs.
References _Omega.
Referenced by MoonIllumSim::Spacecraft.getLongOfAscNode().
        {
            return this._Omega;
        }
double MoonIllumSim::KeplerOrbit::getMeanAnomalyAtEpoch () [inline]
Definition at line 264 of file KeplerOrbit.cs.
References _M0.
Referenced by MoonIllumSim::Spacecraft.getMeanAnomalyAtEpoch().
        {
            return this._M0;
        }
Vector3D MoonIllumSim::KeplerOrbit::getPosition (double t) [inline]
Definition at line 105 of file KeplerOrbit.cs.
References _epoch, _M0, _GM, MoonIllumSim::tools.normalizeAngle(), MoonIllumSim::tools.solveKeplerForE(), _e, _a, _omega, _Omega, and _i.
Referenced by MoonIllumSim::SpacecraftState.setTime().
        {
            double M = 0;
            double dt = 0;
            double E = 0;
            double nu = 0;
            double r_c = 0;
            Vector3D o = new Vector3D();
            //Vector3D d_o = new Vector3D();
            Vector3D r = new Vector3D();
            if (t == this._epoch)
            {
                M = this._M0;
            }
            else
            {
                dt = 86400 * (t - this._epoch);
                M = this._M0 + dt * Math.Sqrt((_GM) / (Math.Pow(this._a, 3)));
                M = tools.normalizeAngle(M);
            }
            E = tools.solveKeplerForE(M, this._e);
            nu = 2 * Math.Atan2(Math.Sqrt(1 + this._e) * Math.Sin(E / 2), Math.Sqrt(1 - this._e) * Math.Cos(E / 2));
            r_c = this._a * (1 - this._e * Math.Cos(E));
            o = r_c * new Vector3D(Math.Cos(nu), Math.Sin(nu), 0);
            //d_o = (Math.Sqrt(_GM * this._a) / r_c) * new Vector3D(-Math.Sin(E), Math.Sqrt(1 - Math.Pow(this._e, 2)) * Math.Cos(E), 0);
            r = new Vector3D(
                    o.x() * (Math.Cos(this._omega) * Math.Cos(this._Omega) - Math.Sin(this._omega) * Math.Cos(this._i) * Math.Sin(this._Omega)) - o.y() * (Math.Sin(this._omega) * Math.Cos(this._Omega) + Math.Cos(this._omega) * Math.Cos(this._i) * Math.Sin(this._Omega)),
                    o.x() * (Math.Cos(this._omega) * Math.Sin(this._Omega) - Math.Sin(this._omega) * Math.Cos(this._i) * Math.Cos(this._Omega)) + o.y() * (Math.Cos(this._omega) * Math.Cos(this._i) * Math.Cos(this._Omega) - Math.Sin(this._omega) * Math.Sin(this._Omega)),
                    o.x() * (Math.Sin(this._omega) * Math.Sin(this._i)) + o.y() * (Math.Cos(this._omega) * Math.Sin(this._i)));
            //Console.WriteLine(o.x().ToString("e"));
            //Console.WriteLine(o.y().ToString("e"));
            //Console.WriteLine(o.z().ToString("e"));
            return r;
        }
double MoonIllumSim::KeplerOrbit::getSemiMajorAxis () [inline]
Definition at line 239 of file KeplerOrbit.cs.
References _a.
Referenced by MoonIllumSim::Spacecraft.getSemiMajorAxis().
        {
            return this._a;
        }
void MoonIllumSim::KeplerOrbit::setEpoch (double epoch) [inline]
Definition at line 217 of file KeplerOrbit.cs.
References _epoch.
Referenced by setKeplerElements(), and MoonIllumSim::Spacecraft.setEpoch().
        {
            if (epoch >= 0)
            {
                this._epoch = epoch;
            }
            else
            {
                throw new Exception("Epoch is less than 0.");
            }
        }
void MoonIllumSim::KeplerOrbit::setKeplerElements (double a, double e, double omega, double Omega, double i, double M0) [inline]
Definition at line 23 of file KeplerOrbit.cs.
References _set_a(), _set_e(), _set_omega(), _set_Omega(), _set_i(), and _set_M0().
Referenced by KeplerOrbit(), and MoonIllumSim::Spacecraft.setKeplerOrbitParameters().
        {
            try
            {
                this._set_a(a);
                this._set_e(e);
                this._set_omega(omega);
                this._set_Omega(Omega);
                this._set_i(i);
                this._set_M0(M0);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
void MoonIllumSim::KeplerOrbit::setKeplerElements (double epoch, double a, double e, double omega, double Omega, double i, double M0) [inline]
Definition at line 40 of file KeplerOrbit.cs.
References setEpoch(), _set_a(), _set_e(), _set_omega(), _set_Omega(), _set_i(), and _set_M0().
        {
            try
            {
                this.setEpoch(epoch);
                this._set_a(a);
                this._set_e(e);
                this._set_omega(omega);
                this._set_Omega(Omega);
                this._set_i(i);
                this._set_M0(M0);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
Member Data Documentation
double MoonIllumSim::KeplerOrbit::_a = 2000000 + _moon_radius [private]
Definition at line 14 of file KeplerOrbit.cs.
Referenced by getPosition(), _set_a(), and getSemiMajorAxis().
double MoonIllumSim::KeplerOrbit::_e = 1 [private]
Definition at line 15 of file KeplerOrbit.cs.
Referenced by getPosition(), _set_e(), and getEccentricity().
double MoonIllumSim::KeplerOrbit::_epoch = 51544.5 [private]
Definition at line 13 of file KeplerOrbit.cs.
Referenced by getPosition(), setEpoch(), getEpoch(), and getEpochAsUTCString().
const double MoonIllumSim::KeplerOrbit::_GM = 4.90277790e+012 [private]
Definition at line 11 of file KeplerOrbit.cs.
Referenced by KeplerOrbit(), and getPosition().
double MoonIllumSim::KeplerOrbit::_i = 0 [private]
Definition at line 18 of file KeplerOrbit.cs.
Referenced by getPosition(), _set_i(), and getInclination().
double MoonIllumSim::KeplerOrbit::_M0 = 0 [private]
Definition at line 19 of file KeplerOrbit.cs.
Referenced by getPosition(), _set_M0(), and getMeanAnomalyAtEpoch().
const double MoonIllumSim::KeplerOrbit::_moon_radius = 1737400 [private]
Definition at line 10 of file KeplerOrbit.cs.
Referenced by _set_a().
double MoonIllumSim::KeplerOrbit::_omega = 0 [private]
Definition at line 16 of file KeplerOrbit.cs.
Referenced by getPosition(), _set_omega(), and getArgumentOfPeriapsis().
double MoonIllumSim::KeplerOrbit::_Omega = 0 [private]
Definition at line 17 of file KeplerOrbit.cs.
Referenced by getPosition(), _set_Omega(), and getLongOfAscNode().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/KeplerOrbit.cs