Moon Surface Illumination Simulation Framework: MoonIllumSim::Simulation Class Reference
MoonIllumSim::Simulation Class Reference
Public Member Functions
void checkConfig ()
void doCalculations ()
void doCalculationsLogic (Spacecraft sc, double time)
double getFOV ()
uint getHeight ()
string getOutputPath ()
string getPatternRepoPath ()
string getPOVPath ()
uint getRes ()
ArrayList getSimulationTime ()
ArrayList getSimulationTimesAsUTCString ()
uint getWidth ()
void setBatchSet (double time, Vector3D pos, Quaternion orientation)
void setBatchSet (double time, Vector3D pos)
void setFOV (double FOV)
void setHeight (uint height)
void setOutputPath (string path)
void setPatternRepoPath (string path)
void setPOVPath (string path)
void setRes (uint res)
void setSimulationTime (double time)
void setSimulationTime (ArrayList times)
void setWidth (uint width)
Public Attributes
Spacecraft spacecraft = new Spacecraft()
Static Protected Attributes
static double _moon_radius = 1737.4
Private Member Functions
void generatePOVRayFile (SpacecraftState sc, string filename)
Private Attributes
double _FOV = 60
uint _height = 1200
string _output_path = "\\output\\"
string _pattern_repos = "\\pattern-repository\\"
string _pov_path = "\\POV-Ray-3.7\\bin\\"
uint _res = 4
ArrayList _simulation_times = new ArrayList()
uint _width = 1600
int loopCount = 1
List< Spacecraft > spacecrafts = new List<Spacecraft>()
Static Private Attributes
static string _dir_exe = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)
static string _dir_MSISF = Directory.GetParent(_dir_exe).FullName
Member Function Documentation
void MoonIllumSim::Simulation::checkConfig () [inline]
Definition at line 30 of file Simulation.cs.
References getOutputPath().
Referenced by MoonIllumSim::Program.Main().
        {
            if (!Directory.Exists(this.getOutputPath()))
            {
                throw new Exception("Output path is not set properly. Please use the -o option.\nPATH: " + this.getOutputPath());
            }
            if (!File.Exists(this.getPOVPath() + @"\pvengine64.exe"))
            {
                throw new Exception("pvengine64.exe could not be found. Please set a valid path via the --pov-path option.\nPATH: " + this.getOutputPath());
            }
            if (!Directory.Exists(this.getPatternRepoPath()))
            {
                throw new Exception("Path to LDEM pattern repository is not set properly. Please use the -p option.\nPATH: " + this.getOutputPath());
            }
        }
void MoonIllumSim::Simulation::doCalculations () [inline]
Definition at line 173 of file Simulation.cs.
References MoonIllumSim::Program.batchSet, spacecrafts, doCalculationsLogic(), MoonIllumSim::Spacecraft.getFixedTime(), getSimulationTime(), and spacecraft.
Referenced by MoonIllumSim::Program.Main().
        {
            if(Program.batchSet)
            {
                foreach(Spacecraft sc in this.spacecrafts)
                {
                    doCalculationsLogic(sc, sc.getFixedTime());
                }
            }
            else
            {
                foreach (double time in this.getSimulationTime())
                {
                    doCalculationsLogic(this.spacecraft, time);
                }
            }
        }
void MoonIllumSim::Simulation::doCalculationsLogic (Spacecraft sc, double time) [inline]
Definition at line 191 of file Simulation.cs.
References MoonIllumSim::Spacecraft.addSpacecraftState(), MoonIllumSim::Spacecraft.getSpacecraftState(), MoonIllumSim::SpacecraftState.getTime(), MoonIllumSim::SpacecraftState.getPosition(), MoonIllumSim::SpacecraftState.getSunPosition(), MoonIllumSim::SpacecraftState.getOrientation(), loopCount, MoonIllumSim::tools.MJDtoUTC(), MoonIllumSim::Vector3D.x(), MoonIllumSim::Program.scientificFormat, MoonIllumSim::tools.m2AU(), MoonIllumSim::Vector3D.y(), MoonIllumSim::Vector3D.z(), MoonIllumSim::Spacecraft.isOrientationGiven(), MoonIllumSim::Quaternion.r(), MoonIllumSim::Quaternion.v(), getOutputPath(), generatePOVRayFile(), _pov_path, _width, and _height.
Referenced by doCalculations().
        {
            int step = sc.addSpacecraftState(time);
            double simTime = sc.getSpacecraftState(step).getTime();
            Vector3D position = sc.getSpacecraftState(step).getPosition();
            Vector3D sun_position = sc.getSpacecraftState(step).getSunPosition();
            Quaternion orientation = sc.getSpacecraftState(step).getOrientation();
            Console.WriteLine("  Simulation time point #" + this.loopCount.ToString("D5") + ": " + simTime + " MJD (" + tools.MJDtoUTC(simTime).ToString("s") + " UTC)");
            Console.WriteLine("  --------------------------------------------------------------------------------------------------------------");
            Console.WriteLine();
            Console.WriteLine("    Calculating spacecraft position at given simulation time...");
            Console.WriteLine("      Result:");
            Console.WriteLine("        x = " + position.x().ToString(Program.scientificFormat) + " m      (" + tools.m2AU(position.x()).ToString(Program.scientificFormat) + " AU)");
            Console.WriteLine("        y = " + position.y().ToString(Program.scientificFormat) + " m      (" + tools.m2AU(position.y()).ToString(Program.scientificFormat) + " AU)");
            Console.WriteLine("        z = " + position.z().ToString(Program.scientificFormat) + " m      (" + tools.m2AU(position.z()).ToString(Program.scientificFormat) + " AU)");
            Console.WriteLine();
            if (sc.isOrientationGiven())
            {
                Console.WriteLine("    Calculating spacecraft orientation at given simulation time...");
                Console.WriteLine("      Result (Quaternion):");
                Console.WriteLine("        q_0 = " + orientation.r().ToString(Program.scientificFormat));
                Console.WriteLine("        q_1 = " + orientation.v().x().ToString(Program.scientificFormat));
                Console.WriteLine("        q_2 = " + orientation.v().y().ToString(Program.scientificFormat));
                Console.WriteLine("        q_3 = " + orientation.v().z().ToString(Program.scientificFormat));
                Console.WriteLine();
            }
            Console.WriteLine("    Calculating Sun position at given simulation time...");
            Console.WriteLine("      Result:");
            Console.WriteLine("        x = " + sun_position.x().ToString(Program.scientificFormat) + " m      (" + tools.m2AU(sun_position.x()).ToString(Program.scientificFormat) + " AU)");
            Console.WriteLine("        y = " + sun_position.y().ToString(Program.scientificFormat) + " m      (" + tools.m2AU(sun_position.y()).ToString(Program.scientificFormat) + " AU)");
            Console.WriteLine("        z = " + sun_position.z().ToString(Program.scientificFormat) + " m      (" + tools.m2AU(sun_position.z()).ToString(Program.scientificFormat) + " AU)");
            Console.WriteLine();
            string filename = this.getOutputPath() + "MoonSurfIllumSim_step_" + this.loopCount.ToString("D5") + ".pov";
            Console.WriteLine("    Ray tracing scene (Dynamical Surface Pattern Selection Algorithm - DSPSA)...");
            this.generatePOVRayFile(sc.getSpacecraftState(step), filename);
            Console.WriteLine("    POV-Ray file written to \"" + filename + "\"");
            Console.WriteLine("    Rendering using POV-Ray...");
            Process pov = new Process();
            pov.StartInfo.FileName = this._pov_path + "pvengine64.exe";
            pov.StartInfo.Arguments = "/EXIT Quality=11 Antialias_Depth=3 Antialias=On Antialias_Threshold=0.1 Jitter_Amount=0.5 Jitter=On Width=" + this._width + " Height=" + this._height + " Antialias=On Antialias_Threshold=0.3 /RENDER \"" + filename + "\"";
            pov.Start();
            pov.WaitForExit();
            Console.WriteLine();
            Console.WriteLine();
            this.loopCount++;
        }
void MoonIllumSim::Simulation::generatePOVRayFile (SpacecraftState sc, string filename) [inline, private]
Definition at line 244 of file Simulation.cs.
References MoonIllumSim::SpacecraftState.getPosition(), MoonIllumSim::SpacecraftState.getSunPosition(), MoonIllumSim::Spacecraft.isOrientationGiven(), MoonIllumSim::Vector3D.QuaternionRotate(), MoonIllumSim::SpacecraftState.getOrientation(), MoonIllumSim::Vector3D.x(), MoonIllumSim::Vector3D.y(), MoonIllumSim::Vector3D.z(), _height, _FOV, _width, MoonIllumSim::Vector3D.norm(), MoonIllumSim::tools.deg2rad(), _moon_radius, MoonIllumSim::tools.rad2deg(), _pattern_repos, and _res.
Referenced by doCalculationsLogic().
        {
            ArrayList filetext = new ArrayList();
            Vector3D scPos = sc.getPosition() / 1000;
            Vector3D sunPos = sc.getSunPosition() / 1000;
            Vector3D skyPos = new Vector3D(0, 0, 1);
            Vector3D lookAt = new Vector3D(0, 0, 0);
            if(sc.isOrientationGiven())
            {
                skyPos = skyPos.QuaternionRotate(sc.getOrientation());
                lookAt = scPos + new Vector3D(-1,0,0).QuaternionRotate(sc.getOrientation());
            }
            filetext.Add("#version 3.7;");
            filetext.Add("");
            filetext.Add("#declare Orange = rgb <1,0.5,0>;");
            filetext.Add("#declare Red = rgb <1,0,0>;");
            filetext.Add("#declare Yellow = rgb <1,1,0>;");
            filetext.Add("#declare moon = texture");
            filetext.Add("                {");
            filetext.Add("                  pigment { color rgb<0.8, 0.8, 0.8> }");
            filetext.Add("                  finish");
            filetext.Add("                  {");
            filetext.Add("                    ambient 0.0");
            filetext.Add("                    diffuse 0.8");
            filetext.Add("                  }");
            filetext.Add("                }");
            filetext.Add("");
            filetext.Add("global_settings");
            filetext.Add("{");
            filetext.Add("   assumed_gamma 1.0");
            filetext.Add("}");
            filetext.Add("");
            filetext.Add("camera");
            filetext.Add("{");
            filetext.Add("  perspective");
            filetext.Add("  location <" + scPos.x() + ", " + scPos.y() + ", " + scPos.z() + ">");
            filetext.Add("  right <-" + (Convert.ToDouble(this._width) / Convert.ToDouble(this._height)).ToString("0.0000000") + ", 0, 0>           // right-handed coordinate system!");
            filetext.Add("  up <0, 1, 0>");
            filetext.Add("  sky <" + skyPos.x() + ", " + skyPos.y() + ", " + skyPos.z() + ">");
            filetext.Add("  angle " + this._FOV.ToString("0.0000000"));
            filetext.Add("  look_at <" + lookAt.x() + ", " + lookAt.y() + ", " + lookAt.z() + ">");
            filetext.Add("}");
            filetext.Add("");
            filetext.Add("light_source");
            filetext.Add("{");
            filetext.Add("  <" + sunPos.x() + ", " + sunPos.y() + ", " + sunPos.z() + ">");
            filetext.Add("  color rgb<1, 1, 1>");
            filetext.Add("  looks_like");
            filetext.Add("  {");
            filetext.Add("    sphere");
            filetext.Add("    {");
            filetext.Add("      0, 1000");
            filetext.Add("      pigment { rgbt 1 }");
            filetext.Add("      hollow");
            filetext.Add("      interior");
            filetext.Add("      {");
            filetext.Add("        media");
            filetext.Add("        {");
            filetext.Add("          emission 1");
            filetext.Add("          density");
            filetext.Add("          {");
            filetext.Add("            spherical");
            filetext.Add("            density_map");
            filetext.Add("            {");
            filetext.Add("              [0 rgb 0]");
            filetext.Add("              [60 Orange]");
            filetext.Add("              [80 Red]");
            filetext.Add("              [100 Yellow]");
            filetext.Add("            }");
            filetext.Add("            scale 1000");
            filetext.Add("          }");
            filetext.Add("        }");
            filetext.Add("      }");
            filetext.Add("    }");
            filetext.Add("  }");
            filetext.Add("}");
            filetext.Add("");
            // Dynamical Surface Pattern Selection Algorithm (DSPSA)
            ArrayList pattern = new ArrayList();
            for (double y = 1; y <= this._height; y++)
            {
                for (double x = 1; x <= this._width; x++)
                {
                    Vector3D right = new Vector3D(0, (Convert.ToDouble(this._width) / Convert.ToDouble(this._height)), 0);
                    Vector3D direction = ((lookAt - scPos) / ((lookAt - scPos).norm())) * ((0.5 * right.norm()) / Math.Tan(tools.deg2rad(this._FOV) / 2)) + (((1 + this._height - (2 * y)) / (2 * this._height)) * skyPos) - (((1 + this._width - (2 * x)) / (2 * this._width)) * right);
                    double discriminant = 4 * Math.Pow(scPos*direction,2) - 4 * (direction*direction) * (scPos*scPos) + 4 * (direction * direction) * Math.Pow(_moon_radius,2);
                    bool encounter = false;
                    double lat = 0;
                    double lon = 0;
                    if (discriminant < 0)
                    {
                        // no encounter
                    }
                    else if (discriminant == 0)
                    {
                        // one intersection
                        encounter = true;
                        double t = (-2 * (scPos * direction)) / (2 * (direction * direction));
                        Vector3D ray_point = scPos + direction * t;
                        lat = tools.rad2deg((Math.PI/2)-Math.Acos(ray_point.z()/_moon_radius));
                        lon = tools.rad2deg(Math.Atan2(ray_point.y(), ray_point.x()));
                    }
                    else
                    {
                        // two intersections
                        encounter = true;
                        double t1 = (-2 * (scPos * direction) + Math.Sqrt(discriminant)) / (2 * (direction * direction));
                        double t2 = (-2 * (scPos * direction) - Math.Sqrt(discriminant)) / (2 * (direction * direction));
                        Vector3D ray_point1 = scPos + direction * t1;
                        Vector3D ray_point2 = scPos + direction * t2;
                        double ray_norm1 = (ray_point1 - scPos).norm();
                        double ray_norm2 = (ray_point2 - scPos).norm();
                        if (ray_norm1 < ray_norm2)
{
                            lat = tools.rad2deg((Math.PI / 2) - Math.Acos(ray_point1.z() / _moon_radius));
                            lon = tools.rad2deg(Math.Atan2(ray_point1.y(), ray_point1.x()));
                        }
                        else
{
                            lat = tools.rad2deg((Math.PI / 2) - Math.Acos(ray_point2.z() / _moon_radius));
                            lon = tools.rad2deg(Math.Atan2(ray_point2.y(), ray_point2.x()));
                        }
                    }
                    if (lon < 0)
                    {
                        lon += 360;
                    }
                    if (encounter)
                    {
                        double lat_start = 0;
                        double lat_end = 0;
                        double lon_start = 0;
                        double lon_end = 0;
                        if (lat >= 0)
{
                            lat_start = Math.Truncate(lat / 5) * 5;
                            lat_end = lat_start + 5;
                        }
                        else
{
                            lat_end = Math.Truncate(lat / 5) * 5;
                            lat_start = lat_end - 5;
                        }
                        lon_start = Math.Truncate(lon / 5) * 5;
                        lon_end = lon_start + 5;
                        string temp = "_lat_" + lat_start + "_" + lat_end + "_lon_" + lon_start + "_" + lon_end;
                        if (!pattern.Contains(temp))
{
                            pattern.Add(temp);
                        }
                    }
                }
            }
            foreach (string str in pattern)
            {
                filetext.Add("#include \"" + this._pattern_repos + "pattern_LDEM_" + this._res + str + ".inc\"");
            }
            /*
            filetext.Add("sphere");
            filetext.Add("{");
            filetext.Add("  <1800,0,0>, 40");
            filetext.Add("  pigment { color rgb<1, 0, 0> }");
            filetext.Add("  finish");
            filetext.Add("  {");
            filetext.Add("    ambient 1.0");
            filetext.Add("    diffuse 1.0");
            filetext.Add("  }");
            filetext.Add("}");
            filetext.Add("sphere");
            filetext.Add("{");
            filetext.Add("  <0,1850,0>, 40");
            filetext.Add("  pigment { color rgb<0, 1, 0> }");
            filetext.Add("  finish");
            filetext.Add("  {");
            filetext.Add("    ambient 1.0");
            filetext.Add("    diffuse 1.0");
            filetext.Add("  }");
            filetext.Add("}");
            */
            TextWriter file = new System.IO.StreamWriter(filename);
            foreach (string line in filetext)
            {
                file.WriteLine(line);
            }
            file.Close();
        }
double MoonIllumSim::Simulation::getFOV () [inline]
Definition at line 138 of file Simulation.cs.
References _FOV.
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._FOV;
        }
uint MoonIllumSim::Simulation::getHeight () [inline]
Definition at line 158 of file Simulation.cs.
References _height.
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._height;
        }
string MoonIllumSim::Simulation::getOutputPath () [inline]
Definition at line 128 of file Simulation.cs.
References _output_path.
Referenced by checkConfig(), doCalculationsLogic(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._output_path;
        }
string MoonIllumSim::Simulation::getPatternRepoPath () [inline]
Definition at line 94 of file Simulation.cs.
References _pattern_repos.
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._pattern_repos;
        }
string MoonIllumSim::Simulation::getPOVPath () [inline]
Definition at line 111 of file Simulation.cs.
References _pov_path.
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._pov_path;
        }
uint MoonIllumSim::Simulation::getRes () [inline]
Definition at line 168 of file Simulation.cs.
References _res.
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._res;
        }
ArrayList MoonIllumSim::Simulation::getSimulationTime () [inline]
Definition at line 59 of file Simulation.cs.
References _simulation_times.
Referenced by doCalculations(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._simulation_times;
        }
ArrayList MoonIllumSim::Simulation::getSimulationTimesAsUTCString () [inline]
Definition at line 64 of file Simulation.cs.
References _simulation_times, and MoonIllumSim::tools.MJDtoUTC().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            ArrayList simulation_times_UTC = new ArrayList();
            for (int i = 0; i < this._simulation_times.Count; i++)
            {
                simulation_times_UTC.Add(tools.MJDtoUTC(Convert.ToDouble(this._simulation_times[i])).ToString("s"));
            }
            return simulation_times_UTC;
        }
uint MoonIllumSim::Simulation::getWidth () [inline]
Definition at line 148 of file Simulation.cs.
References _width.
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._width;
        }
void MoonIllumSim::Simulation::setBatchSet (double time, Vector3D pos, Quaternion orientation) [inline]
Definition at line 446 of file Simulation.cs.
References MoonIllumSim::Spacecraft.setPosition(), MoonIllumSim::Spacecraft.setOrientation(), MoonIllumSim::Spacecraft.setFixedTime(), and spacecrafts.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            Spacecraft sc = new Spacecraft();
            sc.setPosition(pos);
            sc.setOrientation(orientation);
            sc.setFixedTime(time);
            this.spacecrafts.Add(sc);
        }
void MoonIllumSim::Simulation::setBatchSet (double time, Vector3D pos) [inline]
Definition at line 455 of file Simulation.cs.
References MoonIllumSim::Spacecraft.setStateVectors(), and spacecrafts.
        {
            Spacecraft sc = new Spacecraft();
            sc.setStateVectors(pos, new Vector3D(0, 0, 0));
            this.spacecrafts.Add(sc);
        }
void MoonIllumSim::Simulation::setFOV (double FOV) [inline]
Definition at line 133 of file Simulation.cs.
References _FOV.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._FOV = FOV;
        }
void MoonIllumSim::Simulation::setHeight (uint height) [inline]
Definition at line 153 of file Simulation.cs.
References _height.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._height = height;
        }
void MoonIllumSim::Simulation::setOutputPath (string path) [inline]
Definition at line 116 of file Simulation.cs.
References _output_path.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            if (Directory.Exists(path))
            {
                this._output_path = path;
            }
            else
            {
                throw new Exception("Specified output directory could not be found.");
            }
        }
void MoonIllumSim::Simulation::setPatternRepoPath (string path) [inline]
Definition at line 75 of file Simulation.cs.
References _pattern_repos.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            if (Directory.Exists(path))
            {
                if (path.Substring(path.Length-2, 1) != "\\")
                {
                    this._pattern_repos = path + "\\";
                }
                else
                {
                    this._pattern_repos = path;
                }
            }
            else
            {
                throw new Exception("Specified pattern repository could not be found.");
            }
        }
void MoonIllumSim::Simulation::setPOVPath (string path) [inline]
Definition at line 99 of file Simulation.cs.
References _pov_path.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            if (File.Exists(path + @"\pvengine64.exe"))
            {
                this._pov_path = path;
            }
            else
            {
                throw new Exception("Specified POV-Ray path is invalid (pvengine64.exe could not be found).");
            }
        }
void MoonIllumSim::Simulation::setRes (uint res) [inline]
Definition at line 163 of file Simulation.cs.
References _res.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._res = res;
        }
void MoonIllumSim::Simulation::setSimulationTime (double time) [inline]
Definition at line 46 of file Simulation.cs.
References _simulation_times.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._simulation_times.Add(time);
        }
void MoonIllumSim::Simulation::setSimulationTime (ArrayList times) [inline]
Definition at line 51 of file Simulation.cs.
References _simulation_times.
        {
            foreach(double time in times)
            {
                this._simulation_times.Add(time);
            }
        }
void MoonIllumSim::Simulation::setWidth (uint width) [inline]
Definition at line 143 of file Simulation.cs.
References _width.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._width = width;
        }
Member Data Documentation
string MoonIllumSim::Simulation::_dir_exe = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location) [static, private]
Definition at line 18 of file Simulation.cs.
string MoonIllumSim::Simulation::_dir_MSISF = Directory.GetParent(_dir_exe).FullName [static, private]
Definition at line 19 of file Simulation.cs.
double MoonIllumSim::Simulation::_FOV = 60 [private]
Definition at line 23 of file Simulation.cs.
Referenced by setFOV(), getFOV(), and generatePOVRayFile().
uint MoonIllumSim::Simulation::_height = 1200 [private]
Definition at line 25 of file Simulation.cs.
Referenced by setHeight(), getHeight(), doCalculationsLogic(), and generatePOVRayFile().
double MoonIllumSim::Simulation::_moon_radius = 1737.4 [static, protected]
Definition at line 27 of file Simulation.cs.
Referenced by generatePOVRayFile().
string MoonIllumSim::Simulation::_output_path = "\\output\\" [private]
Definition at line 22 of file Simulation.cs.
Referenced by setOutputPath(), and getOutputPath().
string MoonIllumSim::Simulation::_pattern_repos = "\\pattern-repository\\" [private]
Definition at line 20 of file Simulation.cs.
Referenced by setPatternRepoPath(), getPatternRepoPath(), and generatePOVRayFile().
string MoonIllumSim::Simulation::_pov_path = "\\POV-Ray-3.7\\bin\\" [private]
Definition at line 21 of file Simulation.cs.
Referenced by setPOVPath(), getPOVPath(), and doCalculationsLogic().
uint MoonIllumSim::Simulation::_res = 4 [private]
Definition at line 26 of file Simulation.cs.
Referenced by setRes(), getRes(), and generatePOVRayFile().
ArrayList MoonIllumSim::Simulation::_simulation_times = new ArrayList() [private]
Definition at line 17 of file Simulation.cs.
Referenced by setSimulationTime(), getSimulationTime(), and getSimulationTimesAsUTCString().
uint MoonIllumSim::Simulation::_width = 1600 [private]
Definition at line 24 of file Simulation.cs.
Referenced by setWidth(), getWidth(), doCalculationsLogic(), and generatePOVRayFile().
int MoonIllumSim::Simulation::loopCount = 1 [private]
Definition at line 28 of file Simulation.cs.
Referenced by doCalculationsLogic().
Spacecraft MoonIllumSim::Simulation::spacecraft = new Spacecraft()
Definition at line 16 of file Simulation.cs.
Referenced by doCalculations(), MoonIllumSim::tools.parse_arguments(), and MoonIllumSim::tools.output_configuration_overview().
List<Spacecraft> MoonIllumSim::Simulation::spacecrafts = new List<Spacecraft>() [private]
Definition at line 15 of file Simulation.cs.
Referenced by doCalculations(), and setBatchSet().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/Simulation.cs