Moon Surface Illumination Simulation Framework: MoonIllumSim::SpacecraftState Class Reference
MoonIllumSim::SpacecraftState Class Reference
Public Member Functions
int addSpacecraftState (double time)
double getArgumentOfPeriapsis ()
double getEccentricity ()
double getEpoch ()
string getEpochAsUTCString ()
double getFixedTime ()
double getInclination ()
Quaternion getInitialOrientation ()
KeplerOrbit getKeplerOrbit ()
double getLongOfAscNode ()
double getMeanAnomalyAtEpoch ()
Quaternion getOrientation ()
Vector3D getOrientationTransition ()
Vector3D getPosition ()
double getSemiMajorAxis ()
SpacecraftState getSpacecraftState (int i)
Vector3D getSunPosition ()
double getTime ()
bool isOrientationGiven ()
void setEpoch (double epoch)
void setFixedTime (double time)
void setKeplerOrbitParameters (double a, double e, double omega, double Omega, double i, double M0)
void setOrientation (Quaternion orientation)
void setOrientationTransition (Vector3D trans)
void setPosition (Vector3D r)
void setStateVectors (Vector3D r, Vector3D dr)
void setTime (double time)
SpacecraftState (Spacecraft sc)
Public Attributes
Vector3D _fixed_position = new Vector3D(0, 0, 0)
bool fixedPositionGiven = false
Protected Attributes
Quaternion _initial_orientation = new Quaternion(1,0,0,0)
KeplerOrbit _kepler_orbit = new KeplerOrbit()
Quaternion _orientation = new Quaternion(1,0,0,0)
Vector3D _orientation_transition = new Vector3D(0,0,0)
Vector3D _position = new Vector3D()
Vector3D _sun_position = new Vector3D()
double _time = 0
bool orientation_given = false
Private Member Functions
static void calculateSunPosition (string utc, ref double x, ref double y, ref double z)
Vector3D calculateSunPosition ()
Constructor & Destructor Documentation
MoonIllumSim::SpacecraftState::SpacecraftState (Spacecraft sc) [inline]
Definition at line 21 of file SpacecraftState.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, MoonIllumSim::Spacecraft.getKeplerOrbit(), MoonIllumSim::Spacecraft._initial_orientation, MoonIllumSim::Spacecraft.getInitialOrientation(), MoonIllumSim::Spacecraft._orientation_transition, MoonIllumSim::Spacecraft.getOrientationTransition(), MoonIllumSim::Spacecraft.orientation_given, MoonIllumSim::Spacecraft.isOrientationGiven(), MoonIllumSim::Spacecraft._fixed_position, and MoonIllumSim::Spacecraft.fixedPositionGiven.
        {
            this._kepler_orbit = sc.getKeplerOrbit();
            this._initial_orientation = sc.getInitialOrientation();
            this._orientation_transition = sc.getOrientationTransition();
            this.orientation_given = sc.isOrientationGiven();
            this._fixed_position = sc._fixed_position;
            this.fixedPositionGiven = sc.fixedPositionGiven;
        }
Member Function Documentation
int MoonIllumSim::Spacecraft::addSpacecraftState (double time) [inline, inherited]
Definition at line 109 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._spacecraft_state.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic().
        {
            Int32 id = this._spacecraft_state.Count + 1;
            this._spacecraft_state.Add(id, new SpacecraftState(this));
            this._spacecraft_state[id].setTime(time);
            return id;
        }
static void MoonIllumSim::SpacecraftState::calculateSunPosition (string utc, ref double x, ref double y, ref double z) [private]
Vector3D MoonIllumSim::SpacecraftState::calculateSunPosition () [inline, private]
Definition at line 59 of file SpacecraftState.cs.
References MoonIllumSim::tools.MJDtoUTC(), and _time.
Referenced by setTime().
        {
            double x = 0;
            double y = 0;
            double z = 0;
            string UTCString = tools.MJDtoUTC(this._time).ToString("s");
            calculateSunPosition(UTCString, ref x, ref y, ref z);
            return new Vector3D(x, y, z);
        }
double MoonIllumSim::Spacecraft::getArgumentOfPeriapsis () [inline, inherited]
Definition at line 57 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getArgumentOfPeriapsis().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getArgumentOfPeriapsis();
        }
double MoonIllumSim::Spacecraft::getEccentricity () [inline, inherited]
Definition at line 52 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getEccentricity().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getEccentricity();
        }
double MoonIllumSim::Spacecraft::getEpoch () [inline, inherited]
Definition at line 25 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getEpoch().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getEpoch();
        }
string MoonIllumSim::Spacecraft::getEpochAsUTCString () [inline, inherited]
Definition at line 30 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getEpochAsUTCString().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getEpochAsUTCString();
        }
double MoonIllumSim::Spacecraft::getFixedTime () [inline, inherited]
Definition at line 137 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._fixed_simulation_time.
Referenced by MoonIllumSim::Simulation.doCalculations().
        {
            return this._fixed_simulation_time;
        }
double MoonIllumSim::Spacecraft::getInclination () [inline, inherited]
Definition at line 67 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getInclination().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getInclination();
        }
Quaternion MoonIllumSim::Spacecraft::getInitialOrientation () [inline, inherited]
Definition at line 94 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._initial_orientation.
Referenced by SpacecraftState(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._initial_orientation;
        }
KeplerOrbit MoonIllumSim::Spacecraft::getKeplerOrbit () [inline, inherited]
Definition at line 117 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit.
Referenced by SpacecraftState().
        {
            return this._kepler_orbit;
        }
double MoonIllumSim::Spacecraft::getLongOfAscNode () [inline, inherited]
Definition at line 62 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getLongOfAscNode().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getLongOfAscNode();
        }
double MoonIllumSim::Spacecraft::getMeanAnomalyAtEpoch () [inline, inherited]
Definition at line 72 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getMeanAnomalyAtEpoch().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getMeanAnomalyAtEpoch();
        }
Quaternion MoonIllumSim::SpacecraftState::getOrientation () [inline]
Definition at line 76 of file SpacecraftState.cs.
References _orientation.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::Simulation.generatePOVRayFile().
        {
            return this._orientation;
        }
Vector3D MoonIllumSim::Spacecraft::getOrientationTransition () [inline, inherited]
Definition at line 104 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._orientation_transition.
Referenced by SpacecraftState(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._orientation_transition;
        }
Vector3D MoonIllumSim::SpacecraftState::getPosition () [inline]
Definition at line 49 of file SpacecraftState.cs.
References _position.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::Simulation.generatePOVRayFile().
        {
            return this._position;
        }
double MoonIllumSim::Spacecraft::getSemiMajorAxis () [inline, inherited]
Definition at line 47 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.getSemiMajorAxis().
Referenced by MoonIllumSim::tools.output_configuration_overview().
        {
            return this._kepler_orbit.getSemiMajorAxis();
        }
SpacecraftState MoonIllumSim::Spacecraft::getSpacecraftState (int i) [inline, inherited]
Definition at line 122 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._spacecraft_state.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic().
        {
            return this._spacecraft_state[i];
        }
Vector3D MoonIllumSim::SpacecraftState::getSunPosition () [inline]
Definition at line 71 of file SpacecraftState.cs.
References _sun_position.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::Simulation.generatePOVRayFile().
        {
            return this._sun_position;
        }
double MoonIllumSim::SpacecraftState::getTime () [inline]
Definition at line 54 of file SpacecraftState.cs.
References _time.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic().
        {
            return this._time;
        }
bool MoonIllumSim::Spacecraft::isOrientationGiven () [inline, inherited]
Definition at line 127 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft.orientation_given.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), MoonIllumSim::Simulation.generatePOVRayFile(), SpacecraftState(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this.orientation_given;
        }
void MoonIllumSim::Spacecraft::setEpoch (double epoch) [inline, inherited]
Definition at line 20 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.setEpoch().
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._kepler_orbit.setEpoch(epoch);
        }
void MoonIllumSim::Spacecraft::setFixedTime (double time) [inline, inherited]
Definition at line 132 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._fixed_simulation_time.
Referenced by MoonIllumSim::Simulation.setBatchSet().
        {
            this._fixed_simulation_time = time;
        }
void MoonIllumSim::Spacecraft::setKeplerOrbitParameters (double a, double e, double omega, double Omega, double i, double M0) [inline, inherited]
Definition at line 35 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit, and MoonIllumSim::KeplerOrbit.setKeplerElements().
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            try
            {
                this._kepler_orbit.setKeplerElements(a, e, omega, Omega, i, M0);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
void MoonIllumSim::Spacecraft::setOrientation (Quaternion orientation) [inline, inherited]
Definition at line 88 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._initial_orientation, and MoonIllumSim::Spacecraft.orientation_given.
Referenced by MoonIllumSim::Simulation.setBatchSet(), and MoonIllumSim::tools.parse_arguments().
        {
            this._initial_orientation = orientation;
            this.orientation_given = true;
        }
void MoonIllumSim::Spacecraft::setOrientationTransition (Vector3D trans) [inline, inherited]
Definition at line 99 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._orientation_transition.
Referenced by MoonIllumSim::tools.parse_arguments().
        {
            this._orientation_transition = trans;
        }
void MoonIllumSim::Spacecraft::setPosition (Vector3D r) [inline, inherited]
Definition at line 82 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._fixed_position, and MoonIllumSim::Spacecraft.fixedPositionGiven.
Referenced by MoonIllumSim::Simulation.setBatchSet().
        {
            this._fixed_position = r;
            this.fixedPositionGiven = true;
        }
void MoonIllumSim::Spacecraft::setStateVectors (Vector3D r, Vector3D dr) [inline, inherited]
Definition at line 77 of file Spacecraft.cs.
References MoonIllumSim::Spacecraft._kepler_orbit.
Referenced by MoonIllumSim::Simulation.setBatchSet(), and MoonIllumSim::tools.parse_arguments().
        {
            this._kepler_orbit = new KeplerOrbit(r, dr);
        }
void MoonIllumSim::SpacecraftState::setTime (double time) [inline]
Definition at line 31 of file SpacecraftState.cs.
References _time, MoonIllumSim::Spacecraft.fixedPositionGiven, _position, MoonIllumSim::Spacecraft._fixed_position, MoonIllumSim::Spacecraft._kepler_orbit, MoonIllumSim::KeplerOrbit.getPosition(), _sun_position, calculateSunPosition(), _orientation, MoonIllumSim::Spacecraft._orientation_transition, MoonIllumSim::Vector3D.z(), MoonIllumSim::Vector3D.y(), MoonIllumSim::Vector3D.x(), and MoonIllumSim::Spacecraft._initial_orientation.
        {
            this._time = time;
            if (this.fixedPositionGiven)
            {
                this._position = this._fixed_position;
            }
            else
            {
                this._position = this._kepler_orbit.getPosition(time);
            }
            this._sun_position = this.calculateSunPosition();
            this._orientation = new RotationQuaternion(new Vector3D(0, 0, 1), this._orientation_transition.z()) *
                                new RotationQuaternion(new Vector3D(0, 1, 0), this._orientation_transition.y()) *
                                new RotationQuaternion(new Vector3D(1, 0, 0), this._orientation_transition.x()) *
                                this._initial_orientation;
        }
Member Data Documentation
Vector3D MoonIllumSim::Spacecraft::_fixed_position = new Vector3D(0, 0, 0) [inherited]
Definition at line 12 of file Spacecraft.cs.
Referenced by MoonIllumSim::Spacecraft.setPosition(), SpacecraftState(), and setTime().
Quaternion MoonIllumSim::Spacecraft::_initial_orientation = new Quaternion(1,0,0,0) [protected, inherited]
Definition at line 13 of file Spacecraft.cs.
Referenced by MoonIllumSim::Spacecraft.setOrientation(), MoonIllumSim::Spacecraft.getInitialOrientation(), SpacecraftState(), and setTime().
KeplerOrbit MoonIllumSim::Spacecraft::_kepler_orbit = new KeplerOrbit() [protected, inherited]
Definition at line 11 of file Spacecraft.cs.
Referenced by MoonIllumSim::Spacecraft.setEpoch(), MoonIllumSim::Spacecraft.getEpoch(), MoonIllumSim::Spacecraft.getEpochAsUTCString(), MoonIllumSim::Spacecraft.setKeplerOrbitParameters(), MoonIllumSim::Spacecraft.getSemiMajorAxis(), MoonIllumSim::Spacecraft.getEccentricity(), MoonIllumSim::Spacecraft.getArgumentOfPeriapsis(), MoonIllumSim::Spacecraft.getLongOfAscNode(), MoonIllumSim::Spacecraft.getInclination(), MoonIllumSim::Spacecraft.getMeanAnomalyAtEpoch(), MoonIllumSim::Spacecraft.setStateVectors(), MoonIllumSim::Spacecraft.getKeplerOrbit(), SpacecraftState(), and setTime().
Quaternion MoonIllumSim::SpacecraftState::_orientation = new Quaternion(1,0,0,0) [protected]
Definition at line 19 of file SpacecraftState.cs.
Referenced by setTime(), and getOrientation().
Vector3D MoonIllumSim::Spacecraft::_orientation_transition = new Vector3D(0,0,0) [protected, inherited]
Definition at line 14 of file Spacecraft.cs.
Referenced by MoonIllumSim::Spacecraft.setOrientationTransition(), MoonIllumSim::Spacecraft.getOrientationTransition(), SpacecraftState(), and setTime().
Vector3D MoonIllumSim::SpacecraftState::_position = new Vector3D() [protected]
Definition at line 17 of file SpacecraftState.cs.
Referenced by setTime(), and getPosition().
Vector3D MoonIllumSim::SpacecraftState::_sun_position = new Vector3D() [protected]
Definition at line 18 of file SpacecraftState.cs.
Referenced by setTime(), and getSunPosition().
double MoonIllumSim::SpacecraftState::_time = 0 [protected]
Definition at line 16 of file SpacecraftState.cs.
Referenced by setTime(), getTime(), and calculateSunPosition().
bool MoonIllumSim::Spacecraft::fixedPositionGiven = false [inherited]
Definition at line 17 of file Spacecraft.cs.
Referenced by MoonIllumSim::Spacecraft.setPosition(), SpacecraftState(), and setTime().
bool MoonIllumSim::Spacecraft::orientation_given = false [protected, inherited]
Definition at line 16 of file Spacecraft.cs.
Referenced by MoonIllumSim::Spacecraft.setOrientation(), MoonIllumSim::Spacecraft.isOrientationGiven(), and SpacecraftState().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/SpacecraftState.cs