Moon Surface Illumination Simulation Framework: MoonIllumSim::Quaternion Class Reference
MoonIllumSim::Quaternion Class Reference
Provides the data structure, methods and operators to handle quaternions.
Public Member Functions
Quaternion conjugate ()
Vector3D getVector ()
bool isPure ()
double Norm ()
Quaternion ()
Default (empty) constructor for a quaternion.
Quaternion (double real, double x, double y, double z)
Constructor for a quaternion defined by four single double values.
Quaternion (double real, Vector3D vec)
Constructor for a quaternion defined by one double value as real part and a Vector3D as vector part.
double r ()
Vector3D v ()
Static Public Member Functions
static Quaternion operator* (Quaternion q1, Quaternion q2)
static Quaternion operator+ (Quaternion q1, Quaternion q2)
Protected Attributes
double _r = 0
quaternion real part
Vector3D _v = new Vector3D(0,0,0)
quaternion vector part
Detailed Description
Provides the data structure, methods and operators to handle quaternions.
Quaternions are a set of numbers extending the complex numbers. Quaternions not only have one imaginary part, but three of them and therefore they are often called hyper-complex numbers.
The set of quaternions is often denoted as , honoring Sir William Rowan Hamilton, which first described the quaternion algebra. In this documentation the following notation was used:
A quaternion consists of a real part (also called scalar part) and a three-dimensional vector part . A quaternion is written as .
Constructor & Destructor Documentation
MoonIllumSim::Quaternion::Quaternion () [inline]
Default (empty) constructor for a quaternion.
The empty constructor initializes the quaternion as .
Definition at line 44 of file Quaternion.cs.
Referenced by operator+(), operator*(), and conjugate().
{ }
MoonIllumSim::Quaternion::Quaternion (double real, double x, double y, double z) [inline]
Constructor for a quaternion defined by four single double values.
Parameters:
real real part
x x-component of the vector part
y y-component of the vector part
z z-component of the vector part
Definition at line 53 of file Quaternion.cs.
References _r, and _v.
        {
            this._r = real;
            this._v = new Vector3D(x, y, z);
        }
MoonIllumSim::Quaternion::Quaternion (double real, Vector3D vec) [inline]
Constructor for a quaternion defined by one double value as real part and a Vector3D as vector part.
Parameters:
real real part
vec vector part
Definition at line 64 of file Quaternion.cs.
References _r, and _v.
        {
            this._r = real;
            this._v = vec;
        }
Member Function Documentation
Quaternion MoonIllumSim::Quaternion::conjugate () [inline]
Definition at line 93 of file Quaternion.cs.
References Quaternion(), _r, and _v.
Referenced by MoonIllumSim::Vector3D.QuaternionRotate().
        {
            return new Quaternion(this._r, -this._v);
        }
Vector3D MoonIllumSim::Quaternion::getVector () [inline]
Definition at line 98 of file Quaternion.cs.
References isPure(), and _v.
Referenced by MoonIllumSim::Vector3D.QuaternionRotate().
        {
            if (this.isPure())
            {
                return this._v;
            }
            else
            {
                throw new Exception("Error returning vector from Quaternion: Quaternion is not an pure Quaternion.");
            }
        }
bool MoonIllumSim::Quaternion::isPure () [inline]
Definition at line 110 of file Quaternion.cs.
Referenced by getVector().
        {
            /*
            if (this._r == 0)
            {
                return true;
            }
            else
            {
                return false;
            }*/
            return true;
        }
double MoonIllumSim::Quaternion::Norm () [inline]
Definition at line 124 of file Quaternion.cs.
References _r, _v, MoonIllumSim::Vector3D.x(), MoonIllumSim::Vector3D.y(), and MoonIllumSim::Vector3D.z().
        {
            return Math.Sqrt((this._r * this._r) + (this._v.x() * this._v.x()) + (this._v.y() * this._v.y()) + (this._v.z() * this._v.z()));
        }
static Quaternion MoonIllumSim::Quaternion::operator* (Quaternion q1, Quaternion q2) [inline, static]
Definition at line 75 of file Quaternion.cs.
References Quaternion().
        {
            return new Quaternion(  q1.r() * q2.r() - q1.v().x() * q2.v().x() - q1.v().y() * q2.v().y() - q1.v().z() * q2.v().z(),
                                    q1.r() * q2.v().x() + q1.v().x() * q2.r() + q1.v().y() * q2.v().z() - q1.v().z() * q2.v().y(),
                                    q1.r() * q2.v().y() - q1.v().x() * q2.v().z() + q1.v().y() * q2.r() + q1.v().z() * q2.v().x(),
                                    q1.r() * q2.v().z() + q1.v().x() * q2.v().y() - q1.v().y() * q2.v().x() + q1.v().z() * q2.r());
        }
static Quaternion MoonIllumSim::Quaternion::operator+ (Quaternion q1, Quaternion q2) [inline, static]
Definition at line 70 of file Quaternion.cs.
References Quaternion().
        {
            return new Quaternion(q1.r() + q2.r(), q1.v() + q2.v());
        }
double MoonIllumSim::Quaternion::r () [inline]
Definition at line 83 of file Quaternion.cs.
References _r.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._r;
        }
Vector3D MoonIllumSim::Quaternion::v () [inline]
Definition at line 88 of file Quaternion.cs.
References _v.
Referenced by MoonIllumSim::Simulation.doCalculationsLogic(), and MoonIllumSim::tools.output_configuration_overview().
        {
            return this._v;
        }
Member Data Documentation
double MoonIllumSim::Quaternion::_r = 0 [protected]
quaternion real part
Definition at line 31 of file Quaternion.cs.
Referenced by Quaternion(), r(), conjugate(), Norm(), and MoonIllumSim::RotationQuaternion.RotationQuaternion().
Vector3D MoonIllumSim::Quaternion::_v = new Vector3D(0,0,0) [protected]
quaternion vector part
Definition at line 36 of file Quaternion.cs.
Referenced by Quaternion(), v(), conjugate(), getVector(), Norm(), and MoonIllumSim::RotationQuaternion.RotationQuaternion().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/Quaternion.cs