Moon Surface Illumination Simulation Framework: MoonIllumSim::Vector3D Class Reference
MoonIllumSim::Vector3D Class Reference
Public Member Functions
double norm ()
Vector3D QuaternionRotate (Vector3D axis, double angle)
Vector3D QuaternionRotate (Quaternion RotationQuaternion)
void setVector (double x, double y, double z)
Vector3D ()
Vector3D (double x, double y, double z)
double x ()
double y ()
double z ()
Static Public Member Functions
static Vector3D operator% (Vector3D v1, Vector3D v2)
static Vector3D operator* (double s, Vector3D vec)
static Vector3D operator* (Vector3D vec, double s)
static double operator* (Vector3D v1, Vector3D v2)
static Vector3D operator+ (Vector3D v1, Vector3D v2)
static Vector3D operator- (Vector3D v1, Vector3D v2)
static Vector3D operator- (Vector3D vec)
static Vector3D operator/ (Vector3D vec, double s)
Private Attributes
double _x = 0
double _y = 0
double _z = 0
Constructor & Destructor Documentation
MoonIllumSim::Vector3D::Vector3D () [inline]
Definition at line 14 of file Vector3D.cs.
Referenced by operator+(), operator*(), operator%(), operator/(), and operator-().
{ }
MoonIllumSim::Vector3D::Vector3D (double x, double y, double z) [inline]
Definition at line 16 of file Vector3D.cs.
References _x, x(), _y, y(), _z, and z().
        {
            this._x = x;
            this._y = y;
            this._z = z;
        }
Member Function Documentation
double MoonIllumSim::Vector3D::norm () [inline]
Definition at line 88 of file Vector3D.cs.
References _y, and _z.
Referenced by MoonIllumSim::KeplerOrbit.KeplerOrbit(), and MoonIllumSim::Simulation.generatePOVRayFile().
        {
            return Math.Sqrt(Math.Pow(this._x, 2) + Math.Pow(this._y, 2) + Math.Pow(this._z, 2));
        }
static Vector3D MoonIllumSim::Vector3D::operator% (Vector3D v1, Vector3D v2) [inline, static]
Definition at line 51 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(v1.y() * v2.z() - v1.z() * v2.y(),
                                v1.z() * v2.x() - v1.x() * v2.z(),
                                v1.x() * v2.y() - v1.y() * v2.x());
        }
static Vector3D MoonIllumSim::Vector3D::operator* (double s, Vector3D vec) [inline, static]
Definition at line 35 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(s * vec.x(), s * vec.y(), s * vec.z());
        }
static Vector3D MoonIllumSim::Vector3D::operator* (Vector3D vec, double s) [inline, static]
Definition at line 40 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(s * vec.x(), s * vec.y(), s * vec.z());
        }
static double MoonIllumSim::Vector3D::operator* (Vector3D v1, Vector3D v2) [inline, static]
Definition at line 45 of file Vector3D.cs.
        {
            return v1.x() * v2.x() + v1.y() * v2.y() + v1.z() * v2.z();
        }
static Vector3D MoonIllumSim::Vector3D::operator+ (Vector3D v1, Vector3D v2) [inline, static]
Definition at line 30 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(v1.x() + v2.x(), v1.y() + v2.y(), v1.z() + v2.z());
        }
static Vector3D MoonIllumSim::Vector3D::operator- (Vector3D v1, Vector3D v2) [inline, static]
Definition at line 63 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(v1.x() - v2.x(), v1.y() - v2.y(), v1.z() - v2.z());
        }
static Vector3D MoonIllumSim::Vector3D::operator- (Vector3D vec) [inline, static]
Definition at line 68 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(-vec.x(), -vec.y(), -vec.z());
        }
static Vector3D MoonIllumSim::Vector3D::operator/ (Vector3D vec, double s) [inline, static]
Definition at line 58 of file Vector3D.cs.
References Vector3D().
        {
            return new Vector3D(vec.x() / s, vec.y() / s, vec.z() / s);
        }
Vector3D MoonIllumSim::Vector3D::QuaternionRotate (Vector3D axis, double angle) [inline]
Definition at line 93 of file Vector3D.cs.
References MoonIllumSim::Quaternion.conjugate(), _x, _y, _z, and MoonIllumSim::Quaternion.getVector().
Referenced by MoonIllumSim::Simulation.generatePOVRayFile().
        {
            Quaternion RotationQuaternion = new RotationQuaternion(axis, angle);
            Quaternion RotationQuaternionConjugate = RotationQuaternion.conjugate();
            Quaternion vec = new Quaternion(0, this._x, this._y, this._z);
            Quaternion result = RotationQuaternion * vec * RotationQuaternionConjugate;
            return result.getVector();
        }
Vector3D MoonIllumSim::Vector3D::QuaternionRotate (Quaternion RotationQuaternion) [inline]
Definition at line 104 of file Vector3D.cs.
References MoonIllumSim::Quaternion.conjugate(), _x, _y, _z, and MoonIllumSim::Quaternion.getVector().
        {
            Quaternion RotationQuaternionConjugate = RotationQuaternion.conjugate();
            Quaternion vec = new Quaternion(0, this._x, this._y, this._z);
            Quaternion result = RotationQuaternion * vec * RotationQuaternionConjugate;
            return result.getVector();
        }
void MoonIllumSim::Vector3D::setVector (double x, double y, double z) [inline]
Definition at line 23 of file Vector3D.cs.
References _x, x(), _y, y(), _z, and z().
        {
            this._x = x;
            this._y = y;
            this._z = z;
        }
double MoonIllumSim::Vector3D::x () [inline]
Definition at line 73 of file Vector3D.cs.
References _x.
Referenced by MoonIllumSim::KeplerOrbit.KeplerOrbit(), MoonIllumSim::Quaternion.Norm(), MoonIllumSim::RotationQuaternion.RotationQuaternion(), MoonIllumSim::Simulation.doCalculationsLogic(), MoonIllumSim::Simulation.generatePOVRayFile(), MoonIllumSim::SpacecraftState.setTime(), MoonIllumSim::tools.output_configuration_overview(), Vector3D(), and setVector().
        {
            return this._x;
        }
double MoonIllumSim::Vector3D::y () [inline]
Definition at line 78 of file Vector3D.cs.
References _y.
Referenced by MoonIllumSim::KeplerOrbit.KeplerOrbit(), MoonIllumSim::Quaternion.Norm(), MoonIllumSim::RotationQuaternion.RotationQuaternion(), MoonIllumSim::Simulation.doCalculationsLogic(), MoonIllumSim::Simulation.generatePOVRayFile(), MoonIllumSim::SpacecraftState.setTime(), MoonIllumSim::tools.output_configuration_overview(), Vector3D(), and setVector().
        {
            return this._y;
        }
double MoonIllumSim::Vector3D::z () [inline]
Definition at line 83 of file Vector3D.cs.
References _z.
Referenced by MoonIllumSim::KeplerOrbit.KeplerOrbit(), MoonIllumSim::Quaternion.Norm(), MoonIllumSim::RotationQuaternion.RotationQuaternion(), MoonIllumSim::Simulation.doCalculationsLogic(), MoonIllumSim::Simulation.generatePOVRayFile(), MoonIllumSim::SpacecraftState.setTime(), MoonIllumSim::tools.output_configuration_overview(), Vector3D(), and setVector().
        {
            return this._z;
        }
Member Data Documentation
double MoonIllumSim::Vector3D::_x = 0 [private]
Definition at line 10 of file Vector3D.cs.
Referenced by Vector3D(), setVector(), x(), and QuaternionRotate().
double MoonIllumSim::Vector3D::_y = 0 [private]
Definition at line 11 of file Vector3D.cs.
Referenced by Vector3D(), setVector(), y(), norm(), and QuaternionRotate().
double MoonIllumSim::Vector3D::_z = 0 [private]
Definition at line 12 of file Vector3D.cs.
Referenced by Vector3D(), setVector(), z(), norm(), and QuaternionRotate().
The documentation for this class was generated from the following file:
MoonIllumSim/src/main/Vector3D.cs